version: "3"
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - datadb:/var/lib/postgresql
    restart: always

  jenkins:
    container_name: jenkins
    build: jenkins
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - "9000:9000"
    links:
      - db
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always

volumes:
  datadb:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
